name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Swift
        uses: actions/setup-swift@v1
        with:
          swift-version: '6.1'

      - name: Build
        run: swift build --disable-sandbox

      - name: Test
        run: swift test --disable-sandbox

  lint:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  generate-docs:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Swift toolchain
        uses: fwal/setup-swift@v1
        with:
          swift-version: '6.1'

      - name: Generate documentation
        run: |
          swift package \
            --allow-writing-to-directory docs \
            generate-documentation \
            --target Lava \
            --transform-for-static-hosting

      - name: Archive documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs