name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '6.1'
    - name: Install Danger
      run: swift package update && swift run danger-swift ci
    - name: Run Danger
      run: swift run danger-swift ci
    - name: Install Periphery
      run: brew install peripheryapp/periphery/periphery
    - name: Run Periphery
      run: periphery scan --workspace Lava.xcworkspace --schemes Lava

  lint:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftFormat
        run: swiftformat . --dry-run --strict
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict